name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pr-checks:
    runs-on: arc-runner-set  # Ensure this matches your self-hosted runner old entry self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Internal IP Address
        run: |
          echo "Fetching internal IP..."
          INTERNAL_IP=$(hostname -I | awk '{print $1}')
          echo "Internal IP of the runner: $INTERNAL_IP"

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Authenticate with Google Cloud
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project $GOOGLE_PROJECT
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

      - name: Set Up Docker Host
        run: |
          export DOCKER_HOST=tcp://localhost:2376
          docker version  # Check if Docker is accessible

      - name: Build Docker Image
        run: |
          export DOCKER_HOST=tcp://localhost:2376
          docker build -t my-app .

      # - name: Build Docker Image
      #   run: |
      #     docker build -t my-app .
          
      - name: Run Container with GCP Credentials
        run: |
          export DOCKER_HOST=tcp://localhost:2376
          docker run -d \
            -p 8000:8000 \
            --name my-app-container \
            -v $(pwd)/gcp-key.json:/app/gcp-key.json:ro \
            -e GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-key.json \
            my-app
          sleep 12  # Wait for the app to be ready

      - name: Call GCP Workflow
        run: |
          gcloud workflows execute call-private-endpoint \
            --location=europe-central2 \
            --project=writing-practice-app \
            --format=json
          sleep 60  # Wait for 20 seconds before proceeding

      - name: Cleanup
        if: always()
        run: |
          export DOCKER_HOST=tcp://localhost:2376
          docker stop my-app-container || true
          docker rm my-app-container || true
