name: PR Checks

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  pr-checks:
    runs-on: self-hosted  # Ensure this matches your self-hosted runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project $GOOGLE_PROJECT
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Run Container
        run: |
          docker run -d -p 8000:8000 --name my-app-container my-app
          sleep 8  # Wait for the app to be ready

      - name: Call GCP Workflow
        run: |
          gcloud workflows execute call-private-endpoint \
            --location=europe-central2 \
            --project=writing-practice-app \
            --format=json
          sleep 25  # Wait for 20 seconds before proceeding

      - name: Cleanup
        if: always()
        run: |
          docker stop my-app-container || true
          docker rm my-app-container || true
